data:
  raw_path: "data/raw/Datos_proyecto_C1_Spotify_Youtube.csv"
  processed_path: "data/processed/datos_limpios.csv"

target_classification: "viral"
viral_threshold: 150000000  # streams >= 150M = viral

features_numericas:
  - Danceability
  - Energy
  - Key
  - Loudness
  - Speechiness
  - Acousticness
  - Instrumentalness
  - Liveness
  - Valence
  - Tempo
  - Duration_ms
 

features_categoricas:
  - Album_type
  - Licensed
  - official_video

random_state: 42
test_size: 0.2
cv_folds: 5